definitions:
  request.GetAccountInfoReq:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  response.AccountInfo:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
  description: petsminder 账户相关api
  title: 账户相关api API接口文档
  version: v1.0.1
paths:
  /account/login:
    get:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: query
        name: id
        required: true
        type: string
      - description: 请求参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetAccountInfoReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.AccountInfo'
      summary: 获取用户信息
  /api/v1/base/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetAccountInfoReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.AccountInfo'
      summary: 注册
      tags:
      - account
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
