definitions:
  request.GetAccountInfoReq:
    properties:
      id:
        type: string
    type: object
  request.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.RegisterReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  response.AccountInfo:
    properties:
      name:
        type: string
    type: object
  response.LoginResp:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: 账户相关api
  title: 账户相关api API接口文档
  version: v1.0.1
paths:
  /account/getUserInfo:
    get:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetAccountInfoReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.AccountInfo'
      summary: GetAccountInfo 注册
  /base/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginReq'
      - description: 请求参数
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/response.LoginResp'
      summary: Login 注册
  /base/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 请求参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterReq'
      produces:
      - application/json
      responses: {}
      summary: Register 注册
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
