definitions:
  account.GetUserInfoResp:
    properties:
      accountId:
        type: string
      accountName:
        type: string
    type: object
  model.Account:
    properties:
      account_id:
        type: string
      account_name:
        type: string
      created_at:
        type: integer
      id:
        type: integer
      password:
        type: string
      updated_at:
        type: integer
    type: object
info:
  contact: {}
  description: petsminder 账户相关api
  title: 账户相关api API接口文档
  version: v1.0.1
paths:
  /account/addAccount:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Account'
  /account/getAccountInfo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/account.GetUserInfoResp'
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
